### ISSUE TITLE
Email login removed by Jio now. Need to add otp based login

### ISSUE THREAD

**Issue by pushpendra-jain** [botallen/repository.botallen#147]
Now that Jio has removed email based login, addon need to have OTP based login since then only this addon could work.

**Comment by siddhusubbu** [comment]
No, It still works with Login. please reinstall the Repo and try

**Comment by overclock98** [comment]
is there a way we can log in with OTP? Jio not providing jio id for new users. so it is impossible to log in for the jio uses didn't have jio id.

**Comment by siddhusubbu** [comment]
> is there a way we can log in with OTP? Jio not providing jio id for new users. so it is impossible to log in for the jio uses didn't have jio id.

No, My friend, you are wrong. you can still log in with your email id and password. A screenshot is much appreciated.

**Comment by overclock98** [comment]
@siddhusubbu I'm not saying we can't login jio tv on kodi with jio id and password.

for new jio users, jio does not provide jio id. To use jio services now they are using only jio number and OTP. If you try to login on any jio service you can see that login with jio id now not available. I confirmed this with jio customer care also.

So as a new jio user I don't have a jio id or password to log in on kodi. to use jio services I use jio number and otp. there is no options available to generate jio id and password now for new jio users.

I hope it is clear.

**Comment by siddhusubbu** [comment]
No, it is not clear, Because I recently purchased another new sim card for my Mom from Jio on 22-07-2021, and activated it on the same day registered with her Gmail Id and password. I'm able to log in with her Gmail and Password on the Jio TV. What do you say about that?? I can see the Login with Id enabled on my Jio TV app. Only Jio cinema asks for the OTP.

Try this.

Open Jio Tv (Log out if you are logged in already) and Select New User? Sign Up->Enter Jio number->OTP->add Email Id -> create Password. This is how I signed up for my New Jio Simcard with my Email Id & Password. Let me know if you are able to generate the password with the above steps.

Note: Check if MyJio is updated and verified with your email ID. If it is not verified or registered, please update your email and verify it. Now use the same email to signup for the Jio tv app and generate the password.

**Comment by nsas02** [comment]
I have the same issue now. 
- I do no have a Jio SIM, but I do have JioFiber connection
- This JioFiber connection is linked to my Airtel mobile # and my Gmail ID
Problem is that I'm unable to create a password anywhere because it always expects a JioMobile number.

Can you please help me in this situation?

**Comment by siddhusubbu** [comment]
Yes, your current setup is perfect for a JioFiber connection but to watch Jio Tv other than the Jio Setup box It's Impossible without a Valid Jio Sim card. Only valid Jio Sim users can watch Jio TV. First, get a Jio sim and register yourself with the Id and Password, No one knows when they will block the Password login for the Jio tv app too, so better do it fast.

**Comment by nsas02** [comment]
Thanks, have registered my FIL's Jio number using my mail id. I now have a UID and PWD for jio. Thanks

**Comment by SourabhKumawat20** [comment]
> Now that Jio has removed email based login, addon need to have OTP based login since then only this addon could work.

Yes you are right, but you can solve by downloading older version of jio TV app there you can create a account with id password and use it.

**Comment by SourabhKumawat20** [comment]
Yes you are right, jio remote email id and password login from all apps, but you can get it my downloading older version of jio TV there you create ID password
