### ISSUE TITLE
Jio 2.2.0 has a bug with Login button

### ISSUE THREAD

**Issue by siddhusubbu** [botallen/repository.botallen#161]
## Feature request
For Add-on ... [e.g. Jiotv]
I'm submitting a proposal to ...
  - [ ] new feature
  - [*] change an existing feature

After clicking login-> the option OTP or password pops up. When you close the popup instead of choosing those. It chooses the Password login option by default. Please fix this.

**Comment by siddhusubbu** [comment]
Also Noticed this -> After Clicking Login-> the Option Keyboard or Web Pops up. When you close the popup instead of Choosing those. It chooses the Web option by default. Please fix this too.

**Comment by iMro0t** [comment]
Input is taken by Dialog API which Kodi provides and it only returns True or False as a response and for canceling it returns False by default so there is no way to detect whether Dialog canceled or not though there is a new option `yesnotcustom` which returns `-1` if dialog canceled by the user but in our case, it's not useful since we don't have any third option. [Here](https://codedocs.xyz/AlwinEsch/kodi/group__python___dialog.html#ga4541bc893b3ef70391cb299d6f522ccf)

If this doesn't make sense then ignore it. This is all technical stuff
In short, it's not my fault

**Comment by siddhusubbu** [comment]
First of all, I really appreciate your hard work on this. I totally agree and this is just a suggestion and I clearly understand that you have nothing to do with this dialog box which is maintained by Kodi directly.

Thanks!
