### ISSUE TITLE
JioTV+ which credentials will work ?

### ISSUE THREAD

**Issue by ddmakadia1699** [botallen/repository.botallen#32]
I used jio sim only. I had jio giga fiber service but right now I haven't. So can I use my jio sim credential to this jioTV+ ?
I already tried but it didn't work for me ?

**Comment by nepalicana** [comment]
@ddmakadia1699 Hey, I was using the same credentials as in JioTV addon and it was working for me though not all the channels but those which are in the jio networks, give it a try. @botallen Awesome work dude, right now I checked in my iPhone and good to see some movies working like Bahubaali 2 but unfortunately others were not supported in my phone. So I will try out in my pc and let you know. Was waiting for this addon since long time. Awesome job. Keep it up!!! Thanks.

**Comment by botallen** [comment]
It's currently in beta. 

**Known issues:**

* Hotstar premium content will not play and you'll get notification `Hotstar restricted content.` In future you'll be redirect to Disney+ Hotstar plugin and you can play it there if you have appropriate subscription
* Live tv is currently having limited channels playable. zee and viacom (voot) channels are not currently supported. Although star channels are working except sports.

*Note: I'm looking for jio fiber set-top box plan. If you have that and if you are willing to help me to improve this add-on so dm me in discord. It'll be helpful to add those non working channels supported :)*

**Comment by botallen** [comment]
> I used jio sim only. I had jio giga fiber service but right now I haven't. So can I use my jio sim credential to this jioTV+ ?
> I already tried but it didn't work for me ?

I missed to turn on major login functionality that you don't have to re enter your credentials if you have already in jiotv add-on. I forgot in testing :/
