### ISSUE TITLE
jiotv not working on firetv

### ISSUE THREAD

**Issue by parvbarot** [botallen/repository.botallen#87]
You did awesome work. JioTV is not working for Firetv can u make it possible?

**Comment by stephenvaz03** [comment]
> You did awesome work. JioTV is not working for Firetv can u make it possible?

If you are using the JioTV kodi addon on FireTV I would suggest switching to Tivimate to access jiotv by running the proxy using termux or any command line from https://kodi.botallen.com/jiotv as Kodi is very resources hungry and FireTV isn't a highly powered Streaming Device. In order to run binary hop into the discord server where you can find all the instructions.

**Comment by parthdevloper** [comment]
Hello @stephenvaz03 , can You please explain what you are talking about... I have used the (see belo image)
![image](https://user-images.githubusercontent.com/58413215/98832967-7cdaac00-2463-11eb-9d6e-9bf382ba9ce2.png)

every version of jiotv have their own issue with fireTV stick, `2.0.13`  > jiotv service crashed issue,` 2.0.0` Jio tv all channels not working, and Kodi keeps crashing, can you suggest some bulletproof suggestion...

**Comment by iMro0t** [comment]
This issue is fixed in Jiotv v2.0.14.
